name: CI/CD

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        working-directory: infra/eks
        run: |
          terraform init 
          terraform workspace new dev || terraform workspace select dev
      - name: Terraform Format
        working-directory: infra/eks
        run: |
          terraform fmt

      - name: Terraform Plan
        working-directory: infra/eks
        run: |
          terraform plan 

      - name: Terraform Apply
        working-directory: infra/eks
        run: |
          terraform apply -auto-approve

  deploy:
    name: Build image
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.25.3'
        id: install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Update kube config
        run: aws eks update-kubeconfig --name lendsqr-eks --region us-west-1
      - name: Deploy to EKS
        run: |
          kubectl apply -f infra/manifest.yaml
